pipeline:
  test:
    image: alpine
    commands:
      - env

  docker:
    image: plugins/docker
    repo: gigavoid/web-disk-cache
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - $DRONE_COMMIT_BRANCH
